######################## default configuration ####################
baseURL = "https://elljfb.xyz"
title = "Elliot Fagan-Briggs"
theme = "mini"
author = "Elliot Fagan-Briggs"
copyright = "Copyright Â© 2023, Elliot Fagan-Briggs; all rights reserved."
paginate = 20
languageCode = "en"
DefaultContentLanguage = "en"

[params]
  avatar = 'https://pbs.twimg.com/profile_images/970570368376279040/hsZMVovD_400x400.jpg'                 # gravatar email or image url
  name = 'Elliot Fagan-Briggs'
  bio = 'A blog for jotting down my head full of schemes.'
  enableRSS: true
  showPowerBy: false

social: 
    twitter: https://twitter.com/elljfb